### ISSUE TITLE
Terrain noclip

### ISSUE THREAD

**Issue by PaipGD** [mdmgamedev/echelondev#1]
If you go to the desert, and there i a rly high terrain generated, u can use the noclip thingy to noclip through the ground. @mdmgamedev Fix this so fast as u can bcuz there is a rly thin layer for the terrain pls fix

**Comment by mdmgamedev** [comment]
I am aware of the problem, this is a problem with Unity's terrain system, not with the game. I'm working on a fix by smoothing the terrain and fixing the really steep hills which cause the bug.

**Comment by mdmgamedev** [comment]
I have changed the player's collision a bit so it won't have enough space to clip and now it should be fixed

**Comment by mdmgamedev** [comment]
Nope, it is a bug. Still working on a fix

**Comment by mdmgamedev** [comment]
Meh, the issue just occurs. There is no fix.

**Comment by PaipGD** [comment]
?
u can do nothing bout it? ok, well it's a feature now :)

**Comment by mdmgamedev** [comment]
k fine
